name: flutter_garden
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  bloc: 8.0.3
  flutter_bloc: 8.0.1
  bloc_test: 9.0.3
  get_it: 7.2.0 # We could use injectable
  freezed_annotation: 1.1.0
  # dartz: 0.10.1
  floor: 1.2.0
  auto_route: 3.2.4
  intl: 0.17.0
  modal_bottom_sheet: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4
  build_runner: 2.1.10
  freezed: 1.1.0
  floor_generator: 1.2.0
  auto_route_generator: 3.2.3

flutter:
  uses-material-design: true